"""added distance and duration column

Revision ID: 1fdb70ebc729
Revises: 2a5d2a99b9ed
Create Date: 2023-06-15 15:10:47.929056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fdb70ebc729'
down_revision = '2a5d2a99b9ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_end_mid', sa.Integer(), nullable=True))
        batch_op.drop_column('duration_start_end')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_start_end', sa.INTEGER(), nullable=True))
        batch_op.drop_column('duration_end_mid')

    # ### end Alembic commands ###
