"""added columns to Places

Revision ID: 25fad9657312
Revises: 7e18745b06da
Create Date: 2023-06-28 17:23:29.494441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fad9657312'
down_revision = '7e18745b06da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
