"""added distance and duration columns

Revision ID: 2a5d2a99b9ed
Revises: e66ebbe81829
Create Date: 2023-06-15 15:06:43.137689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5d2a99b9ed'
down_revision = 'e66ebbe81829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distance_start_mid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distance_end_mid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_start_mid', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_start_end', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('duration_start_end')
        batch_op.drop_column('duration_start_mid')
        batch_op.drop_column('duration')
        batch_op.drop_column('distance_end_mid')
        batch_op.drop_column('distance_start_mid')

    # ### end Alembic commands ###
