"""added valid user

Revision ID: 400a6b43afcc
Revises: 1f5bd2abbe88
Create Date: 2023-06-14 11:54:08.981618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400a6b43afcc'
down_revision = '1f5bd2abbe88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_user', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('valid_user')

    # ### end Alembic commands ###
