"""added columns to Places

Revision ID: 515a90ba7d40
Revises: eef2549d9a1b
Create Date: 2023-06-28 16:37:39.738916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515a90ba7d40'
down_revision = 'eef2549d9a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('place_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('place_id')

    # ### end Alembic commands ###
