"""removed valid user

Revision ID: 7e91e66ef27d
Revises: 400a6b43afcc
Create Date: 2023-06-14 13:56:29.031912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e91e66ef27d'
down_revision = '400a6b43afcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('valid_user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valid_user', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
