"""updated friendship table

Revision ID: d0e8bc91c657
Revises: 733c4191e932
Create Date: 2023-06-22 16:42:08.716368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0e8bc91c657'
down_revision = '733c4191e932'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requester_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requested_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('accepted', sa.Boolean(), nullable=True))
        batch_op.drop_constraint('fk_friend_requests_friend_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_friend_requests_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_friend_requests_requested_id_users'), 'users', ['requested_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_friend_requests_requester_id_users'), 'users', ['requester_id'], ['id'])
        batch_op.drop_column('friend_id')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('friend_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_friend_requests_requester_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_friend_requests_requested_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_friend_requests_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_friend_requests_friend_id_users', 'users', ['friend_id'], ['id'])
        batch_op.drop_column('accepted')
        batch_op.drop_column('created_at')
        batch_op.drop_column('requested_id')
        batch_op.drop_column('requester_id')

    # ### end Alembic commands ###
