"""added coordinate columns

Revision ID: e66ebbe81829
Revises: 20b9cde38046
Create Date: 2023-06-15 13:03:33.084623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66ebbe81829'
down_revision = '20b9cde38046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_coords', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('end_coords', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('midpoint_coords', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('midpoint_coords')
        batch_op.drop_column('end_coords')
        batch_op.drop_column('start_coords')

    # ### end Alembic commands ###
