"""added columns to Places

Revision ID: eef2549d9a1b
Revises: 1d279c2addc0
Create Date: 2023-06-28 16:13:28.626042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef2549d9a1b'
down_revision = '1d279c2addc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.drop_column('opening_hours')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_hours', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
